robur-coop/mollymawk

- .github/workflows/format.yml
- .ocamlformat
- albatross_json.ml
- config.ml
- index.ml
- unikernel.ml
expectation for this PR is to fail (since the code isn't ocamlformat-formatted).
//cc @PizieDust
> add ocamlformat github action

- config.ml
- storage.ml
- unikernel.ml
- user_model.ml
//cc @PizieDust
The assumption is: we can retain the stuff in memory. We write to disk on change (at the moment, whenever a new user is created). We keep a reference to the latest store in unikernel.ml (request_handler) - thus we can extract data from `!store`.
We read the store only once at startup (since later we know about each change and don't need to read again).
Obviously we can have more data (and more types) in there ;)
> Initial draft to store users persistently using oneffs

- unikernel.ml
- user_model.ml
- utils.ml
This is an attempt at my proposal to user a randomly generated uuid for the email verification token. This is stored as part of the user data. //cc @PizieDust -- this is a PR against #13
> store email verification uuid in user model, use a random uuid

- middleware.ml
Otherwise, httpaf lets the connection hang and the other end waits for TCP close until timeout /o\ Fixes #62 (I hope)
> Middleware: respond with content-length

- assets/main.js
- middleware.ml
- settings_page.ml
- sign_up.ml
- unikernel.ml
- unikernel_create.ml
- unikernel_single.ml
- update_policy.ml
- user_single.ml
- utils.ml
- verify_email.ml
closes #40 
This PR adds functionality for CSRF token.
When a user is authenticated, we use a [Double Synchronizer Pattern](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern) which keeps the token on the server and transmit a copy as hidden field to the form. 
When a user is not authenticated, we use a [Naive Double Submit Cookie Pattern](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#naive-double-submit-cookie-pattern-discouraged) which sends the token in a cookie and also a hidden field on the form.
We also add a custom header `X-MOLLY-CSRF`. Will experiment with this to see if it's better for unauthenticated users than cookies.
> Csrf tokens

- unikernel_single.ml
The data was swapped according to the table header. That is, the network name internal to the unikernel was displayed under the title "Host Device" while the host bridge name was displayed under "Name".
> Swap around host device and net name

- middleware.ml
this is more a question, whether it is fine to remove these String.trim? #67
> do not String.trim on cookies

- albatross_json.ml
- configuration.ml
- unikernel.ml
- utils.ml
These are two commits:
- the first removes the remaining usage of Yojson.Basic.Utils.member
- it also passes the json_dict directly around from extract_csrf_token, leading to fewer indentation
The second commit uses Yojson.Basic.to_string instead of Yojson.Safe.to_string. I don't know exactly why we should use which - but I counted the usages, and there were more Basic usages.
For #66
> Json refactorings

- assets/main.js
- dashboard.ml
- middleware.ml
- settings_page.ml
- sign_in.ml
- sign_up.ml
- unikernel.ml
- unikernel_create.ml
- unikernel_single.ml
- update_policy.ml
- user_account.ml
- user_model.ml
- user_single.ml
closes #86 #85 
This PR adds buttons to close single sessions and also a logout button.
> Logout functionality

- user_model.ml
also handle the `Null case in string_or_none
> improve error messages for invalid json

- assets/main.js
- storage.ml
- tokens_index.ml
- tokens_ui.ml
- unikernel.ml
- user_model.ml
- utils.ml
related to #38 
This PR begins the work for allowing accessing mollymawk solely via it's API.
API tokens are no longer created when a user creates an account. 
The user can manually create an API token from their dashboard. 
The API tokens now have new fields:
- `name` : to help the user differentiate between different keys e.g (GitHub, GitLab)
- `last_access`: when last was the specific key used to query mollymawk
- `usage_count`: how many times this key has been used
> Token Management

- assets/main.js
- error_page.ml
- middleware.ml
- storage.ml
- unikernel.ml
- user_account.ml
- user_model.ml
- utils.ml
closes #38 
This PR introduces many changes, including a refactoring of how we check for `csrf` tokens. 
In this PR:
- We can now have both session authentication and api token authentication (both stateful and stateless)
- Routes which change state are all converted to POST requests so that we can do the appropriate verifications.
The following endpoints can be accessed via the API
> Api authentication with tokens

- .github/workflows/format.yml
- This updates our ocamlformat workflow to use `setup-ocamlv3`
- We have some issues with the `darcs` package which causes the ci workflow to fail.  Specifically, the error is
> Use setup-ocamlv3 in ocamlformat workflow

- .ocamlformat
- albatross_json.ml
- builder_web.ml
- configuration.ml
- storage.ml
- unikernel.ml
- unikernel_update.ml
- user_model.ml
- utils.ml
update to ocamlformat 0.27.0
/cc @PizieDust
> in builder_web: ptime.t is not optional, report error if the json didn't contain a valid ptime.t

- assets/main.js
fixes https://github.com/robur-coop/mollymawk/issues/101
There was a minor error in the `POST` url. Previously we used an implementation with `GET` which required us to pass the unikernel name in the url, but now with a `POST` implementation, we no longer have to pass the name in the url. 
Restart functionality currently fails due to a non-mollymawk issue which is currently reported at https://github.com/robur-coop/albatross/issues/209
> Fix restart

- assets/main.js
When doing requests in the frontend to the server specify the accept header with appropriate types. For example, if we expect json let the server know. This allows the server to generate errors that are json objects.
> Use accept: application/json

- albatross_json.ml
- assets/main.js
- storage.ml
- unikernel.ml
- unikernel_single.ml
- unikernel_update.ml
- user_model.ml
- utils.ml
This PR implements Rollback functionality for unikernel updates.
The methodology is that, if we try to update a unikernel, we store some metadata about the running unikernel to disk and then attempt the update. If this fails, we call the rollback function with the previous running build.
> Rollback functionality of Unikernels

- assets/main.js
- builder_web.ml
- liveliness_checks.ml
- unikernel.ml
- unikernel_update.ml
- utils.ml
This PR adds new functionality for performing liveliness checks with automatic rollback functionality.
During an update, the user selects which type of liveliness check they want (HTTP, DNS or TCP) and provides an address. This address is then checked that it returns a positive response and then the update is performed, else a rollback is performed. 
At the moment, HTTP and DNS checks have been implemented.
> Perform Liveliness checks

- account_usage.ml
- assets/main.js
- unikernel.ml
- unikernel_create.ml
- update_policy.ml
- utils.ml
This PR redesigns the form used to deploy unikernels. Previously all unikernel configurations were given as a a json string. Now the UI is more intuitive with a form element handling each part of the configuration: for instance selecting network interfaces and block devices, a toggle for fail_behaviour and a dropdown for cpuids etc.
> Better create form fixed

- unikernel_create.ml
- update_policy.ml
- utils.ml
This Pr fixes some minor issues including:
- unikernel deploy ui:  move input for names of devices to the left
-  unikernel deploy ui:  move `+`button for memory to the right
- edit policy ui:  move `+`button for allowed_unikernels,  memory and storage  to the right
> Some ui fixes

- unikernel_create.ml
- update_policy.ml
In the ui elements with a `-` and `+` buttons, manually typing a value reorders this as the cursor slides to the beginning. This PR fixes that.
> Prevent sliding cursors

- unikernel.ml
I also changed the default port to 80 instead of 8080. I think that makes more sense for unikernels, but less so when testing with the unix target. Please feel free to change it to 8080.
> Make port number an argument

- volume_ui.ml
same as #132, but for the block device UI (block size)
> prevent another sliding cursor
